declare module '@vue-js-cron/ant'
declare module '@vue-js-cron/element-plus'
declare module '@vue-js-cron/light'
declare module '@vue-js-cron/quasar'
declare module '@vue-js-cron/vuetify'
declare module 'vuetify/styles'
